// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdoyeslluxnruwdhuauk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkb3llc2xsdXhucnV3ZGh1YXVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNjUzOTksImV4cCI6MjA2NTk0MTM5OX0.Rhvrbn58UCfmwUgXxKMiHP-vqLwdtihSEGBDYL4iutg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);